# Generated by Django 5.2.15 on 2026-07-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('tag', models.CharField(default='AI Pick', max_length=50)),
                ('tag_color', models.CharField(default='#3B82F6', max_length=30)),
                ('price', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=4.9)),
                ('reviews', models.IntegerField(default=1000)),
                ('score', models.IntegerField(default=95)),
                ('image', models.URLField(max_length=500)),
                ('coords', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=30)),
                ('badge', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('best_season', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_recommendation', models.CharField(blank=True, max_length=200, null=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(default='Sparkles', max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('accent', models.CharField(default='#3B82F6', max_length=30)),
                ('metric', models.CharField(max_length=50)),
                ('detail_points', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_id', models.CharField(max_length=20, unique=True)),
                ('destination', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('IN FLIGHT', 'In Flight'), ('BOARDING', 'Boarding'), ('ON SCHEDULE', 'On Schedule'), ('DELAYED', 'Delayed'), ('LANDED', 'Landed')], default='IN FLIGHT', max_length=20)),
                ('status_color', models.CharField(default='#06B6D4', max_length=30)),
                ('passenger', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=20)),
                ('flight', models.CharField(max_length=50)),
                ('eta', models.CharField(max_length=50)),
                ('altitude', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('origin', models.CharField(blank=True, max_length=150, null=True)),
                ('aircraft', models.CharField(blank=True, max_length=100, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=50)),
                ('estimated_cost', models.CharField(max_length=50)),
                ('ai_match_score', models.IntegerField(default=95)),
                ('summary', models.TextField()),
                ('days_data', models.JSONField(default=list)),
                ('included_perks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('avatar', models.URLField(max_length=500)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('trips', models.IntegerField(default=10)),
                ('badge', models.CharField(max_length=50)),
            ],
        ),
    ]
